# Docker Compose override for development environment
version: '3.8'

services:
  # Development configuration for the app
  app:
    build:
      target: development
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    volumes:
      # Mount source code for hot reloading
      - ..:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    command: ["npm", "run", "dev"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Development PostgreSQL with exposed port
  postgres:
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=uap_voting_dev
    volumes:
      # Mount local database scripts for development
      - ../database:/opt/database:ro
      - postgres_dev_data:/var/lib/postgresql/data

  # Development pgAdmin
  pgadmin:
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@uap-bd.edu
      - PGADMIN_DEFAULT_PASSWORD=dev
    ports:
      - "5050:80"

volumes:
  postgres_dev_data:
    driver: local
